### ISSUE TITLE
I have to add the <Mention> Component before the <TinyMCE> component

### ISSUE THREAD

**Issue by luisrudge** [Kindling/react-tinymce-mention#11]
this works:

```js
<Mention {...mentionOptions} />
<TinyMCE {...editorOptions} />
```

this doesn't:

```js
<TinyMCE {...editorOptions} />
<Mention {...mentionOptions} />
```

error: 
![image](https://cloud.githubusercontent.com/assets/941075/20637686/5a5a0ebc-b376-11e6-9c30-a25ad224e4e0.png)

**Comment by deltamualpha** [comment]
https://github.com/Kindling/react-tinymce-mention#troubleshooting Noted in the readme.

**Comment by luisrudge** [comment]
I'm using `react-tinymce` though :(

**Comment by deltamualpha** [comment]
¯\\\_(ツ)_/¯

**Comment by homerlex** [comment]
FYI - I am having the same issue (using react-tinymce from cdn.tinymce.com/4/tinymce.min.js).

**Comment by deltamualpha** [comment]
It's possible that there is naming confusion when using a pre-built or the CDN version of the TinyMCE js file. Loading the plugin first ensures it loads the react version instead of some other version. Alternatively, look at how you're defining plugins for TinyMCE and see if you can't define it as a local version instead of one living on the CDN.
